# Generated by Django 5.1.5 on 2025-03-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('T', 'Top'), ('B', 'Bottom'), ('O', 'Outerwear'), ('F', 'Footwear'), ('A', 'Accessory')], max_length=1)),
                ('colour', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=10)),
                ('material', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
