# Generated by Django 5.1.5 on 2025-03-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clodes', '0003_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
